services:
    deno_api:
        container_name: api
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - TZ=America/Sao_Paulo
            - AWS_REGION=${AWS_REGION}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - S3_EXTERNAL_ENDPOINT=${S3_EXTERNAL_ENDPOINT}
            - S3_BUCKET_NAME=${S3_BUCKET_NAME}
        volumes:
            - ./server:/app
            - ./common:/common
            - deno-cache:/deno-dir
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        depends_on:
            - localstack

    localstack:
        container_name: storage
        image: localstack/localstack
        ports:
            - "127.0.0.1:4566:4566" # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559" # external services port range
        environment:
            - TZ=America/Sao_Paulo
            - S3_SKIP_SIGNATURE_VALIDATION=0
            - S3_BUCKET_NAME=${S3_BUCKET_NAME}
            - API_CORS_ORIGIN=${API_CORS_ORIGIN}
        volumes:
            - "./scrípts/localstack:/etc/localstack/init/ready.d"
            - "./.ls-data:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

    c2pa_worker:
        restart: always
        build:
            context: ./workers/c2pa
            dockerfile: Dockerfile
        environment:
            - S3_BUCKET_NAME=${S3_BUCKET_NAME}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_REGION=${AWS_REGION}
            - S3_INTERNAL_ENDPOINT=${S3_INTERNAL_ENDPOINT}
        volumes:
            - ./workers/c2pa:/worker/c2pa
            - ./common:/common
            - deno-cache:/deno_dir
        depends_on:
            - deno_api

    optimizer_worker:
        restart: always
        build:
            context: ./workers/optimizer
            dockerfile: Dockerfile
        depends_on:
            - deno_api

volumes:
    deno-cache: